steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: GetCreds
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '--project=${PROJECT_ID}'
  - '--region=australia-southeast1'
  - '${_CLUSTER_NAME}'
  
# This step deploys the new version of our container image
# in the hello-cloudbuild Kubernetes Engine cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'kubernetes.yaml'
  